language: python
sudo: false

install:
    # Install gf and requirements
    - bash install.sh
    - . /home/travis/miniconda/etc/profile.d/conda.sh
    - conda info --envs
    - conda activate gf
    - pwd
    - cp .gfail_defaults_travis /home/travis/.gfail_defaults
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - py.test --cov=.
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
