name: gf
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.0=py_0
  - alabaster=0.7.10=py35_1
  - altair=1.2.1=py_0
  - asn1crypto=0.24.0=py35_0
  - attrs=17.4.0=py_0
  - babel=2.5.3=py35_0
  - backcall=0.1.0=py_0
  - basemap=1.1.0=py35_4
  - basemap-data-hires=1.1.0=0
  - beautifulsoup4=4.6.0=py35_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - blinker=1.4=py_0
  - boto3=1.6.22=py_0
  - botocore=1.9.23=py_0
  - branca=0.2.0=py_1
  - bzip2=1.0.6=1
  - ca-certificates=2018.1.18=0
  - cairo=1.14.6=5
  - cartopy=0.16.0=py35_0
  - certifi=2018.1.18=py35_0
  - cffi=1.11.5=py35_0
  - chardet=3.0.4=py35_0
  - click=6.7=py_1
  - click-plugins=1.0.3=py35_0
  - cligj=0.4.0=py35_0
  - coverage=4.5.1=py35_0
  - cryptography=2.2.1=py35_0
  - curl=7.59.0=0
  - cycler=0.10.0=py35_0
  - dask-core=0.17.2=py_0
  - decorator=4.2.1=py35_0
  - descartes=1.1.0=py_1
  - docutils=0.14=py35_0
  - entrypoints=0.2.3=py35_1
  - et_xmlfile=1.0.1=py35_0
  - expat=2.1.0=3
  - feedgenerator=1.9=py35_0
  - fiona=1.7.11=py35_1
  - folium=0.5.0=py_0
  - fontconfig=2.12.1=6
  - freetype=2.7=2
  - freexl=1.0.5=0
  - future=0.16.0=py35_0
  - gdal=2.1.3=py35_7
  - geos=3.6.2=1
  - gettext=0.19.8.1=0
  - ghp-import=0.5.5=py35_0
  - giflib=5.1.4=0
  - glib=2.51.4=0
  - gmp=6.1.2=0
  - graphite2=1.3.11=0
  - h5py=2.7.1=py35_3
  - harfbuzz=1.4.3=0
  - hdf4=4.2.13=0
  - hdf5=1.10.1=2
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - idna=2.6=py35_1
  - imageio=2.3.0=py35_0
  - imagesize=1.0.0=py35_0
  - impactutils=0.8.1=1
  - ipykernel=4.8.2=py35_0
  - ipython=6.3.0=py35_0
  - ipython_genutils=0.2.0=py35_0
  - jdcal=1.3=py35_0
  - jedi=0.11.1=py35_0
  - jinja2=2.10=py35_0
  - jmespath=0.9.3=py35_0
  - jpeg=9b=2
  - json-c=0.12.1=0
  - jsonschema=2.6.0=py35_1
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.7=4
  - krb5=1.14.6=0
  - libcomcat=1.2.1=py35_0
  - libdap4=3.18.3=2
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libnetcdf=4.4.1.1=10
  - libpng=1.6.28=2
  - libpq=9.6.3=0
  - libsodium=1.0.16=0
  - libspatialite=4.3.0a=18
  - libssh2=1.8.0=2
  - libtiff=4.0.9=0
  - libxml2=2.9.8=0
  - libxslt=1.1.32=0
  - lxml=4.2.1=py35_0
  - lzo=2.10=0
  - mapio=0.7.3=0
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py35_0
  - matplotlib=1.5.3=np113py35_8
  - mistune=0.8.3=py_0
  - more-itertools=4.1.0=py_0
  - munch=2.2.0=py35_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py35_0
  - ncurses=5.9=10
  - networkx=2.1=py35_0
  - nose=1.3.7=py35_2
  - notebook=5.4.1=py35_0
  - numexpr=2.6.4=py35_1
  - numpy=1.13.3=py35_blas_openblas_201
  - obspy=1.1.0=py35_1
  - olefile=0.45.1=py35_0
  - openblas=0.2.20=7
  - openjpeg=2.1.2=3
  - openpyxl=2.5.1=py35_0
  - openssl=1.0.2n=0
  - owslib=0.16.0=py_0
  - packaging=17.1=py_0
  - pandas=0.22.0=py35_0
  - pandoc=2.1.3=0
  - pandocfilters=1.4.1=py35_0
  - pango=1.40.4=0
  - paramiko=2.4.1=py35_0
  - parso=0.1.1=py_0
  - pcre=8.41=1
  - pelican=3.7.1=py35_0
  - pexpect=4.4.0=py35_0
  - pickleshare=0.7.4=py35_0
  - pillow=4.2.1=py35_0
  - pip=9.0.3=py35_0
  - pixman=0.34.0=1
  - pluggy=0.6.0=py_0
  - proj4=4.9.3=5
  - prompt_toolkit=1.0.15=py35_0
  - ptyprocess=0.5.2=py35_0
  - py=1.5.3=py_0
  - pyasn1=0.4.2=py_0
  - pycparser=2.18=py35_0
  - pycrypto=2.6.1=py35_1
  - pyepsg=0.3.2=py35_0
  - pygments=2.2.0=py35_0
  - pynacl=1.1.2=py35_0
  - pyopenssl=17.5.0=py35_1
  - pyparsing=2.2.0=py35_0
  - pyproj=1.9.5.1=py35_0
  - pyqt=4.11.4=py35_3
  - pyshp=1.2.12=py_0
  - pysocks=1.6.8=py35_1
  - pytables=3.4.2=py35_7
  - pytest=3.5.0=py35_0
  - pytest-cov=2.5.1=py35_0
  - pytest-mpl=0.9=py_0
  - python=3.5.4=2
  - python-dateutil=2.6.1=py35_0
  - pytz=2018.3=py_0
  - pywavelets=0.5.2=py35_1
  - pyyaml=3.12=py35_1
  - pyzmq=17.0.0=py35_4
  - qt=4.8.7=7
  - rasterio=0.36.0=py35_2
  - readline=6.2=0
  - requests=2.18.4=py35_1
  - s3transfer=0.1.13=py35_0
  - scikit-image=0.13.1=py35_0
  - scikit-learn=0.19.1=py35_blas_openblas_201
  - scipy=1.0.1=py35_blas_openblas_200
  - send2trash=1.5.0=py_0
  - setuptools=39.0.1=py35_0
  - shapely=1.6.4=py35_0
  - simplegeneric=0.8.1=py35_0
  - sip=4.18=py35_1
  - six=1.11.0=py35_1
  - snowballstemmer=1.2.1=py35_0
  - snuggs=1.4.1=py35_0
  - sphinx=1.7.2=py35_0
  - sphinxcontrib-websupport=1.0.1=py35_0
  - sqlalchemy=1.2.6=py35_0
  - sqlite=3.13.0=1
  - terminado=0.8.1=py35_0
  - testpath=0.3.1=py35_0
  - tk=8.5.19=2
  - toolz=0.9.0=py_0
  - tornado=5.0.1=py35_1
  - traitlets=4.3.2=py35_0
  - typing=3.6.4=py35_0
  - unidecode=1.0.22=py35_0
  - urllib3=1.22=py35_0
  - vega=0.4.4=py35_1
  - vincent=0.4.4=py35_0
  - wcwidth=0.1.7=py35_0
  - webencodings=0.5=py35_0
  - wheel=0.31.0=py35_0
  - xerces-c=3.2.0=0
  - xlrd=1.1.0=py_2
  - xlsxwriter=1.0.2=py_0
  - xlwt=1.3.0=py35_0
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - bcrypt=3.1.4=py35ha35c455_0
  - configobj=5.0.6=py35_0
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - util-linux=2.21=0
  - pip:
    - dask==0.17.2
    - groundfailure==0.1.dev0
    - pockets==0.6.2
    - sphinx-argparse==0.2.2
    - sphinx-rtd-theme==0.2.4
    - sphinxcontrib-napoleon==0.6.1
    - tables==3.4.2

