name: gf
channels:
- conda-forge
- defaults
dependencies:
- affine
- basemap
- basemap-data-hires
- branca
- configobj
- descartes
- fiona
- folium
- gdal
- h5py
- lxml
- markdown
- matplotlib
- numpy
- obspy
- pandas
- pelican
- pytables
- pytest
- pytest-cov
- pytest-mpl
- python=3.5
- pyyaml
- rasterio
- scipy
- scikit-learn
- scikit-image
- shapely
- sphinx
- mapio
- impactutils
- libcomcat
- pip:
  - et-xmlfile
  - prompt-toolkit
  - sphinx-argparse
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
